server:
  port: 9000
  
spring:
  application:
    name: login
  datasource:
    url: jdbc:mysql://localhost:3306/Student?createDatabaseIfNotExist=true
    username: root
    password: Current-Root-Password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update      

